services:
  db:
    container_name: "${PROJECT_NAME}_db"
    image: mysql:5.7
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    ports:
      - "${LOCAL_DB_PORT}:3306"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - br0

  wordpress:
    container_name: "${PROJECT_NAME}_${WP_CONTAINER}"
    build:
      context: "./docker/wordpress"
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    depends_on:
      - db
    ports:
      - "${LOCAL_SERVER_PORT}:80"
    restart: unless-stopped
    volumes:
      # wordpressのイメージはvar/www/htmlが想定パスとなる
      - ./resources:/var/www/html
      - ./scripts/wp:/var/www/scripts/wp
      - ./docker/wordpress/php.ini:/usr/local/etc/php/php.ini
    environment:
      - WORDPRESS_DB_NAME=${DB_DATABASE}
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_USE=${DB_USERNAME}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    working_dir:
      /var/www/html/${WP_SUB_DIR}
    networks:
      - br0

  phpmyadmin:
    container_name: "${PROJECT_NAME}_phpmyadmin"
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "3333:80"
    volumes:
      - phpmyadmin_sessions:/sessions
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: ${DB_HOST}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - br0

  mailhog:
    container_name: "${PROJECT_NAME}_mailhog"
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - br0

  # frontend:
  #   container_name: "${PROJECT_NAME}_{FRONT_CONTAINER}"
  #   build:
  #     context: .
  #     dockerfile: docker/frontend/Dockerfile
  #     args:
  #       HOST_UID: ${HOST_UID:-1000}
  #       HOST_GID: ${HOST_GID:-1000}
  #   user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
  #   volumes:
  #     # プロジェクトのファイルをマウント
  #     - ./resources:/var/www/html
  #     # node_modulesはボリュームとしてマウント
  #     - node_modules:/var/www/html/node_modules
  #   working_dir: /var/www/html
  #   ports:
  #     - "${FRONT_PORT}:${FRONT_PORT}"
  #   # ネットワークを揃えてプロキシする
  #   networks:
  #     - br0
  #   # コマンド（コンテナを停めない）
  #   stdin_open: true
  #   tty: true
  #   command: /bin/bash

  # vnu:
  #   container_name: "${PROJECT_NAME}_vnu"
  #   image: ghcr.io/validator/validator:latest
  #   ports:
  #     - "${VNU_PORT:-8888}:8888"
  #   networks:
  #     - br0

volumes:
  db_data:
  phpmyadmin_sessions:
  node_modules:

networks:
  br0:
    driver: bridge